import { getVisibleCollaborationTasks } from '@/lib/services/collaboration-phase2.service'
import { getVisibleCollaborationProjects } from '@/lib/services/collaboration-project.service'
export default async function CollaborationTasksPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams
  const value = (key: string) => typeof params[key] === 'string' ? params[key] as string : undefined
  const tasks = await getVisibleCollaborationTasks({ projectId: value('project'), status: value('status'), priority: value('priority'), overdue: value('overdue') === '1', mine: value('mine') === '1' })
  const projects = await getVisibleCollaborationProjects()
  return <div><h1 className="text-3xl font-600 tracking-tight">Aufgaben</h1><p className="mt-2 text-sm text-muted-foreground">Offene und erledigte Aufgaben aus freigegebenen Projekten.</p><form className="mt-6 flex flex-wrap gap-2 rounded-xl border border-stone-200 bg-white p-4"><select name="project" defaultValue={value('project') ?? ''} className="rounded border border-stone-300 px-2 py-1.5 text-sm"><option value="">Alle Projekte</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select><select name="status" defaultValue={value('status') ?? ''} className="rounded border border-stone-300 px-2 py-1.5 text-sm"><option value="">Alle Status</option><option value="TODO">Offen</option><option value="IN_PROGRESS">In Bearbeitung</option><option value="DONE">Erledigt</option><option value="BLOCKED">Blockiert</option></select><select name="priority" defaultValue={value('priority') ?? ''} className="rounded border border-stone-300 px-2 py-1.5 text-sm"><option value="">Alle Prioritäten</option><option value="URGENT">Dringend</option><option value="HIGH">Hoch</option><option value="MEDIUM">Mittel</option><option value="LOW">Niedrig</option></select><label className="flex items-center gap-2 px-2 text-sm"><input type="checkbox" name="overdue" value="1" defaultChecked={value('overdue') === '1'} /> Überfällig</label><label className="flex items-center gap-2 px-2 text-sm"><input type="checkbox" name="mine" value="1" defaultChecked={value('mine') === '1'} /> Meine Aufgaben</label><button className="rounded bg-stone-800 px-3 py-1.5 text-sm text-white">Filtern</button></form><div className="mt-4 overflow-x-auto rounded-xl border border-stone-200 bg-white shadow-sm"><table className="min-w-full text-left text-sm"><thead className="border-b border-stone-200 text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-5 py-3">Aufgabe</th><th className="px-5 py-3">Projekt / Phase</th><th className="px-5 py-3">Verantwortlich</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Fälligkeit</th></tr></thead><tbody className="divide-y divide-stone-100">{tasks.map((task) => <tr key={task.id}><td className="px-5 py-3"><p className="font-600">{task.title}</p><p className="text-xs text-muted-foreground">{task.isRequired ? 'Erforderlich' : 'Optional'} · {task.priority}</p></td><td className="px-5 py-3">{task.project.name} · {task.stage.title}</td><td className="px-5 py-3">{task.responsibleMembership?.user ? `${task.responsibleMembership.user.firstName} ${task.responsibleMembership.user.lastName}` : 'Nicht zugewiesen'}</td><td className="px-5 py-3">{task.status}</td><td className="px-5 py-3">{task.dueDate?.toLocaleDateString('de-DE') ?? '—'}</td></tr>)}</tbody></table>{tasks.length === 0 && <p className="px-5 py-8 text-sm text-muted-foreground">Keine Aufgaben vorhanden.</p>}</div></div>
}
